version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: MyAddressBook
      POSTGRES_PASSWORD: password # Change this to a secure password for production
      POSTGRES_USER: ludwig
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

volumes:
  database_data:
